SHOW DATABASES;
USE latihan2;
SHOW TABLES;
CREATE TABLE mahasiswa (nim int, nama varchar(15), jenis_kelamin enum('pria', 'wanita'), tgl_lahir date, jalan varchar(15), kodepos int, no_hp int, kd_ds int); 
DESC mahasiswa;
ALTER TABLE mahasiswa ADD PRIMARY KEY (nim);
ALTER TABLE mahasiswa ADD CONSTRAINT fk_dosen FOREIGN KEY (kd_ds) REFERENCES dosen (kd_ds);
CREATE TABLE dosen (kd_ds int, nama varchar(15));
DESC dosen;
ALTER TABLE dosen ADD PRIMARY KEY (kd_ds);
CREATE TABLE mata_kuliah (kd_mk int, nama varchar(15), sks int, primary key (kd_mk));
DESC mata_kuliah;
CREATE TABLE jadwal_mengajar (kd_ds int, kd_mk int, hari date, jam time, ruang varchar(5));
ALTER TABLE jadwal_mengajar ADD PRIMARY KEY (kd_ds, kd_mk);
DESC jadwal_mengajar;
ALTER TABLE jadwal_mengajar ADD CONSTRAINT fk_ds FOREIGN KEY (kd_ds) REFERENCES dosen (kd_ds);
ALTER TABLE jadwal_mengajar ADD CONSTRAINT fk_mk FOREIGN KEY (kd_mk) REFERENCES mata_kuliah (kd_mk);
SHOW CREATE TABLE jadwal_mengajar;
CREATE TABLE krs_mahasiswa (nim int, kd_mk int, kd_ds int, semester int, nilai int);
ALTER TABLE krs_mahasiswa ADD PRIMARY KEY (nim, kd_mk, kd_ds);
DESC krs_mahasiswa;
SHOW CREATE TABLE krs_mahasiswa;